<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand_Choose Module</name>
   <tag></tag>
   <elementGuidId>73227667-106b-4770-b472-892c2e761eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-levelIdAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;formAdd&quot;]/div[2]/div[2]/span/span[1]/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c673163-e0c8-431e-91f5-772ce941dfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>da89faae-4bbb-44e9-ba4f-5fdb7b19141e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-levelIdAdd-container</value>
      <webElementGuid>8af4be20-ae1c-452a-96aa-62a86d3f22be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Level --</value>
      <webElementGuid>6b41ac73-bd99-419f-880a-b910a14a1506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-levelIdAdd-container&quot;)</value>
      <webElementGuid>89e0ef24-901e-411e-9e7e-e3e5d63ce145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-levelIdAdd-container']</value>
      <webElementGuid>4aec3155-ae23-4df7-b9e3-c6e6ab163dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>4f231228-6300-42f5-9bdd-b95f71f30794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>aaabbc56-eba0-4e25-b6ae-5bfa571fe45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-levelIdAdd-container' and (text() = '-- Choose Level --' or . = '-- Choose Level --')]</value>
      <webElementGuid>cd14b613-c3d5-43ad-a1ad-a11fb8f7d756</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
