<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand_Choose Level</name>
   <tag></tag>
   <elementGuidId>21b00c9c-00d9-40a2-9c88-fe7232d1ac5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-levelIdAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;formAdd&quot;]/div[2]/div[1]/div/span/span[1]/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e3bf693-4742-4932-bed6-630e7249047e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>59c3d0e3-3224-46e6-b0ab-a877fe1be7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-levelIdAdd-container</value>
      <webElementGuid>50021774-868d-443c-9e86-af6b811878af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Level --</value>
      <webElementGuid>946424c5-4b5a-4e92-b2af-ce53528f6cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-levelIdAdd-container&quot;)</value>
      <webElementGuid>6ecea47a-3912-4967-8e5b-f9dc7c6f35f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-levelIdAdd-container']</value>
      <webElementGuid>3f0513cd-a38f-4af2-a771-9b37f2f88ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>00d4b5ac-6a56-4ce7-8c1f-7083ff7f552f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>d235b86b-6c78-4ab1-bf8a-f5fb75ef4dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-levelIdAdd-container' and (text() = '-- Choose Level --' or . = '-- Choose Level --')]</value>
      <webElementGuid>8095c80a-b8d6-477a-aa86-9c170eb32c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
