<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_isActive</name>
   <tag></tag>
   <elementGuidId>bb96829a-eb70-4e0d-b18d-4a3c2fa6f608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isActiveAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isActiveAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b23ea92f-f118-49eb-ba2f-552a5618dcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4a4fca19-1cbb-4746-8ac9-74a30a6c5ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9e2745ba-5d39-4f49-8627-43fe12c0c8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isActive</value>
      <webElementGuid>ec3bd301-eda1-4142-ab37-e05352eaa83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isActiveAdd</value>
      <webElementGuid>1a55d1fc-6049-4496-97d7-56f2feca31e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isActiveAdd&quot;)</value>
      <webElementGuid>ebd0befd-c1a0-4f60-9503-111b38d09ae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isActiveAdd']</value>
      <webElementGuid>d5abc495-d6d0-40ab-9166-33d8de0000d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/input</value>
      <webElementGuid>1fc41a23-13f5-4803-93e5-792340f6b0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/form/div[2]/div[4]/input</value>
      <webElementGuid>90838bd8-0909-43a1-ae3e-d2e9c07f3494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'isActive' and @id = 'isActiveAdd']</value>
      <webElementGuid>c3c87036-4d4c-4347-93bf-8d1f31452e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
